### ISSUE TITLE
vignettes not found in R session

### ISSUE THREAD

**Issue by papsti** [bbolker/McMasterPandemic#11]
@davidearn:
```
> library(McMasterPandemic)
> vignette("McMasterPandemic-intro",package="McMasterPandemic")
Warning message:
vignette ‘McMasterPandemic-intro’ not found 
> vignette("getting_started",package="McMasterPandemic")
Warning message:
vignette ‘getting_started’ not found 
> browseVignettes("McMasterPandemic")
No vignettes found by browseVignettes("McMasterPandemic")
```

**Comment by bbolker** [comment]
This is a standard problem when loading via `devtools`, I think ... try building/installing the old-fashioned way and see if that makes a difference? (`R CMD build McMasterPandemic; R CMD INSTALL McMasterPandemic_x.y.z.tar.gz`).  I have encountered this issue before and find it very annoying, wonder if there's something on the interwebs (or more specifically in Wickham's "R Packages" book) that discusses this ... ?

**Comment by papsti** [comment]
Still getting a vignette building issue using `R CMD build`:

```
[irenambp:~/git-repos/McMasterPandemic] papst% R CMD build .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘McMasterPandemic’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘calibration.rmd’ using rmarkdown
--- finished re-building ‘calibration.rmd’

--- re-building ‘farr.rmd’ using rmarkdown
--- finished re-building ‘farr.rmd’

--- re-building ‘model.rmd’ using rmarkdown
--- finished re-building ‘model.rmd’

--- re-building ‘testing_flow.rmd’ using rmarkdown
Warning in png::readPNG(path, native = TRUE, info = TRUE) :
  libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
--- finished re-building ‘testing_flow.rmd’

--- re-building ‘getting_started.Rnw’ using knitr

********************************************************
Note: As of version 1.0.0, cowplot does not change the
  default ggplot2 theme anymore. To recover the previous
  behavior, execute:
  theme_set(theme_cowplot())
********************************************************


Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Loading required namespace: directlabels
Failed with error:  'there is no package called 'directlabels''
Quitting from lines 315-339 (getting_started.Rnw)
Error: processing vignette 'getting_started.Rnw' failed with diagnostics:
please install directlabels package
--- failed re-building ‘getting_started.Rnw’

SUMMARY: processing the following file failed:
  ‘getting_started.Rnw’

Error: Vignette re-building failed.
Execution halted
```

Does `directlabels` just need to be listed under "Suggests" in the DESCRIPTION file?

Not sure how to get/generate the tarball to test your other suggestion. 

In any case, I have a copy of the compiled getting started vignette from DE via email; I made this issue just to flag the problem since it's occurring for me on a fresh install.

**Comment by papsti** [comment]
Ah, `directlabels` is already in there. I'm stumped.

**Comment by bbolker** [comment]
Do you in fact have `directlabels` installed locally?

**Comment by papsti** [comment]
I didn't (duh, sorry!) but after I installed `directlabels`, the vignettes still didn't getting built after I used `devtools::build()` and `devtools::install()`: neither threw any errors and both printed messages that seemed to indicate the vignettes were created/installed properly.

`R CMD build McMasterPandemic; R CMD INSTALL McMasterPandemic_x.y.z.tar.gz` did the trick, though, as you suggested.

**Comment by bbolker** [comment]
`devtools::install()` has `build_vignettes=FALSE` as a default.  Try `devtools::install(build_vignettes=TRUE)` ?

**Comment by papsti** [comment]
That seems to have re-built the vignette!

It's a little confusing because `devtools::install()` and `devtools::install(build_vignettes=TRUE)` both spit out `** installing vignettes` (the only printed message pertaining to vignettes). The subtle difference between "building" and "installing" a vignette was not immediately apparent to me as an R package beginner.

So I guess in theory, `devtools::build()` followed by `devtools::install(build_vignettes=TRUE)` should work, though I'm not sure how to simulate a clean install to check (without actually uninstalling/reinstalling).

**Comment by davidearn** [comment]
Irena,
In case you're not aware, there is a Makefile.  My routine is:

make doc-update
make install

This does everything, including building and installing vignettes.
Of course, it is useful to know how to do everything from within RStudio
too.
David

**Comment by bbolker** [comment]
Uninstalling is pretty easy (`R CMD REMOVE McMasterPandemic` from the command line) if you want to try it.

**Comment by papsti** [comment]
Thanks for the uninstall tip, BB. I can confirm that `devtools::build()` followed by `devtools::install(build_vignettes=TRUE)` builds the vignettes properly. And thanks for the `make` workflow, DE. That works for me as well.
