### ISSUE TITLE
Issues with the install

### ISSUE THREAD

**Issue by ahurford** [bbolker/McMasterPandemic#14]
Thanks for writing this package. I am struggling with the install. Below are my error messages:

> install.packages("MacmasterPandemic")
Warning in install.packages :
  package ‘MacmasterPandemic’ is not available for this version of R

I upgraded to the latest version of R, but still this error. Version is 4.0.3 Bunny Wunnies Freak Out.

Then I tried the remote install. There was some error about deleting a file LOCK000 which I did, and then this subsequent error:

The downloaded binary packages are in
	/var/folders/65/tffydg9n7hjchr4f9k26gv000000gp/T//RtmpVDn38e/downloaded_packages
✓  checking for file ‘/private/var/folders/65/tffydg9n7hjchr4f9k26gv000000gp/T/RtmpVDn38e/remotes6e89250827d4/bbolker-McMasterPandemic-d13f7f9/DESCRIPTION’ (1.1s)
─  preparing ‘McMasterPandemic’: (827ms)
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (365ms)
─  checking for empty or unneeded directories
   Removed empty directory ‘McMasterPandemic/misc’
   Removed empty directory ‘McMasterPandemic/notes’
   Removed empty directory ‘McMasterPandemic/ontario’
   Removed empty directory ‘McMasterPandemic/sandbox’
─  building ‘McMasterPandemic_0.0.16.tar.gz’
   
* installing *source* package ‘McMasterPandemic’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Warning: namespace ‘McMasterPandemic’ is not available and has been replaced
by .GlobalEnv when processing object ‘ont_cal1’
Warning: namespace ‘McMasterPandemic’ is not available and has been replaced
by .GlobalEnv when processing object ‘ont_cal1’
Warning: namespace ‘McMasterPandemic’ is not available and has been replaced
by .GlobalEnv when processing object ‘ont_cal_2brks’
Warning: namespace ‘McMasterPandemic’ is not available and has been replaced
by .GlobalEnv when processing object ‘ont_cal_2brks’
Warning: namespace ‘McMasterPandemic’ is not available and has been replaced
by .GlobalEnv when processing object ‘ont_cal_mob1’
Warning: namespace ‘McMasterPandemic’ is not available and has been replaced
by .GlobalEnv when processing object ‘ont_cal_mob1’
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘bbmle’ 1.0.23.1 is being loaded, but >= 1.0.23.5 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘McMasterPandemic’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/McMasterPandemic’
Error: Failed to install 'McMasterPandemic' from GitHub:
  (converted from warning) installation of package ‘/var/folders/65/tffydg9n7hjchr4f9k26gv000000gp/T//RtmpVDn38e/file6e897945b695/McMasterPandemic_0.0.16.tar.gz’ had non-zero exit status

**Comment by davidearn** [comment]
Amy,

You have spelt McMaster incorrectly.  You tried:

install.packages("MacmasterPandemic")

whereas you need

install.packages("McMasterPandemic")

David

**Comment by ahurford** [comment]
Thanks David. It's true my spelling is terrible, none-the-less, I am still struggling with all the same issues, with the correct spelling.

**Comment by bbolker** [comment]
The specific problem is

> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
namespace ‘bbmle’ 1.0.23.1 is being loaded, but >= 1.0.23.5 is required

Try

```
remotes::install_github("bbolker/bbmle")
remotes::install_github("bbolker/McMasterPandemic")
```

We need to clarify this in the README ...

**Comment by davidearn** [comment]
I was about to write again in the same vein... McMasterPandemic is not on 
CRAN.  You must use install_github as Ben says below.

David

**Comment by davidearn** [comment]
Sorry not to catch that the first time...
David

**Comment by ahurford** [comment]
Yay - that worked! Thank you - Ben and David your software support is fantastic! I'm going to do this and Caroline's one, and we have the Memorial one which is basically the New Zealand one (by Mike Plank). I guess they're all the same? At least, I would like to find out to what extent they all give the same thing. Thanks again.

**Comment by athale** [comment]
Thank you very much for the effort to not just put together this package but really make an effort to make it accessible. The model forecasting is quite amazing!

To test this out for our regional dynamics in S.W. India I installed the R-package of the McMAsterPandemic (ver. 0.0.17) on a MAC Book Pro 10.13.6 with R 4.0.3 GUI 1.73  run via the console. 

I can see the help. But oddly I cannot get the simulation running. Some background, I use Python, C++ and MATLAB for simulations of dynamical systems, but I think I'm stumped on how to run R-simulations. 

Any pointers to get it running would be helpful.
Cheers
Chaitanya
