### ISSUE TITLE
Minor getting_started.Rnw errors

### ISSUE THREAD

**Issue by Apeirogons** [bbolker/McMasterPandemic#17]
Sorry for minor documentation stuff, but I was trying to get started and ran into some potential issues:

Error thrown on line 439, `    , sim_args = list(ndt = 2)`.  - is the comma supposed to be there?
On line 20, include=FALSE does not seem to hide the code block as intended. echo=FALSE fixes this for me.

Are these errors being replicated by anyone else, or is it just weirdness on my end?

**Comment by bbolker** [comment]
You're definitely right about the second.  Not sure about the first.

As for the other, I haven't bothered to check, but there's no harm in `echo=FALSE`.

Not sure why this wasn't getting caught by testing/GitHub Actions?
