### ISSUE TITLE
Check test coverage with the covr package

### ISSUE THREAD

**Issue by papsti** [bbolker/McMasterPandemic#19]
[covr package](https://cran.r-project.org/web/packages/covr/vignettes/how_it_works.html)

BB: "see where we have holes and try to improve test coverage generally"

**Comment by Apeirogons** [comment]
McMasterPandemic Coverage: 69.04%
R/zzz.R: 0.00%
R/utils.R: 51.03%
R/calibrate.R: 54.19%
R/ageify.R: 61.90%
R/impsamp.R: 67.16%
R/methods.R: 70.46%
R/testify.R: 82.88%
R/sim_funs.R: 87.44%
R/kfuns.R: 96.49%
R/afuns.R: 98.67%
