### ISSUE TITLE
Create snapshot tests to identify if a functionality is changing.

### ISSUE THREAD

**Issue by Apeirogons** [bbolker/McMasterPandemic#23]

**Comment by bbolker** [comment]
This may be too general a rubric.  Our tests fall roughly into these categories:

- unit tests (for some very basic properties that we can identify)
- regression tests (i.e., identify a problem, fix it, write a test to make sure it doesn't happen again without our noticing)
- snapshot tests as you're specifying here, e.g. see [here](https://github.com/bbolker/McMasterPandemic/blob/master/tests/testthat/test-basic.R#L19-L34); these are generally by running `dput()` on the output of a command ...

**Comment by Apeirogons** [comment]
I thought that it might be easier to write tests if they used testthis::expect_snapshot (similar to what you did, but automatically logging outputs). I should have put that in the issue; of course, other types of tests will have to be done as well.

**Comment by bbolker** [comment]
I agree. I didn't know about `expect_snapshot()`.  If I were starting this project all over I might try `tinytest` instead of `testthat`, but since we're set up for `testthat` already we should make use of its capabilities ...
