### ISSUE TITLE
add test for negative state values

### ISSUE THREAD

**Issue by Apeirogons** [bbolker/McMasterPandemic#25]
This can be pretty lightweight, i.e. `if any(state<0) ...` throw a warning.  Could allow negative values as big as e.g. `sqrt(.Machine$double.eps)` ?

**Comment by Apeirogons** [comment]
I put a warning check on run_sim_range and run_sim for now. These appear to be working correctly.

If I put a warning check in do_step, it throws no matter what on make_state - maybe someone can help me understand why?

(assuming state variables start with a capital letter for run_sim; is this a bad assumption)?

**Comment by bbolker** [comment]
We need to work on this some more.  Right now we are getting warnings very widely, which breaks the GH actions tests (any WARNING or ERROR counts as failure).

- I will try to see what's going on with `make_state()`
- It's possible that we really *are* seeing lots of negative values, and we have all along, but never noticed them.  If this is intrinsic we may want to switch to `do_hazard=TRUE` as the default?

**Comment by davidearn** [comment]
Irena has mentioned being concerned about negative values.  I forgot about 
do_hazard, so I'm copying her on this response.
David

**Comment by bbolker** [comment]
That's fine. I think she's ahead of you (we've discussed `do_hazard` and I think she's using it now ...)

**Comment by Apeirogons** [comment]
I added a debug feature to the warning (requires utils::capture.output), which prints the problematic lines during the warning message. After my next commit passes CI checking, I'll add the PR. I think we are indeed seeing lots of true negative values (at least during the checks at the end of run_sim).

This code snippet now throws the following warning:
```
library(McMasterPandemic)
params1 <- read_params("ICU1.csv")
state1 <- make_state(params = params1)
sdate <- "2020-02-10"
edate <- "2020-06-01"
state1['S'] <- 0
params1['N'] <- sum(state1)
run_sim(params = params1, state = state1, start_date = sdate, end_date = edate)
```
Warning messages:
1: In (function (params, state = make_state(params[["N"]], params[["E0"]]),  :
  End of run_sim_range check: One or more state variables is negative, below -sqrt(.Machine$double.eps)
2: In run_sim(params = params1, state = state1, start_date = sdate,  :
  End of run_sim check: One or more state variables is negative at some time, below -sqrt(.Machine$double.eps). Check following message for details 
```
           date S            E            I             H           ICU        R         hosp          X         death          D
46  2020-03-26 0 2.009967e-04 -0.003727276  4.134171e-03  2.464178e-03 4.986611  0.001381197 0.06746951  1.686418e-05 0.01031695
48  2020-03-28 0 1.311236e-04 -0.007065876  3.575882e-03  2.223978e-03 4.990766  0.001375730 0.06749745  1.016344e-05 0.01036913
50  2020-03-30 0 8.554067e-05 -0.009540405  3.108972e-03  2.011201e-03 4.993925  0.001371890 0.06751696  4.848301e-06 0.01041002
52  2020-04-01 0 5.580390e-05 -0.011372478  2.719215e-03  1.822570e-03 4.996333  0.001369199 0.06753057  6.491205e-07 0.01044199
54  2020-04-03 0 3.640461e-05 -0.012727596  2.394286e-03  1.655168e-03 4.998175  0.001367316 0.06754005 -2.656783e-06 0.01046692
56  2020-04-05 0 2.374916e-05 -0.013729091  2.123623e-03  1.506428e-03 4.99958 [... truncated]
```

and the test-methods Jacobian test throws a warning in run_sim_range:
```
Warning (test-methods.R:12:5): Jacobian/r/etc
End of run_sim_range check: One or more state variables is negative, below -sqrt(.Machine$double.eps) 
 Check following message for details 
             S             E            Ia            Ip            Im            Is             H            H2          ICUs 
 0.000000e+00  7.404805e-12  1.198787e-08 -7.092199e-02  7.301694e-02  3.419472e-03 -2.387551e-04  5.856031e-06 -2.228587e-05 
         ICUd             D             R             X 
-3.825571e-05  3.522387e-03  9.912566e-01  2.206617e-02 
attr(,"class")
[1] "state_pansim"
```

**Comment by bbolker** [comment]
The problem (or *a* problem) is quite clear if we look at `plot(r, keep_state="I")`

```r
r1 <- run_sim(params = params1, state = state1, start_date = sdate, end_date = edate)
r2 <- update(r1,dt=0.005) ## slow; warning about lack of testing for dt != 1
r3 <- update(r1,step_args=list(do_hazard=TRUE))
library(tidyverse)
m <- map_dfr(list(basic=r1,lo_dt=r2,hazard=r3), ~ select(.,date,I), .id="method")
ggplot(m, aes(date,I,colour=method)) + geom_line()
```
![m](https://user-images.githubusercontent.com/78918/117983043-966e8a80-b304-11eb-82c8-7e93bbb54f93.png)

**Comment by bbolker** [comment]
Switch to `do_hazard=TRUE` (+ `fix_pars`) as default ... ?

**Comment by Apeirogons** [comment]
The "old" and "new" calibrations are far too different for the differences to be explained by numerical instability - the pipeline must be different. I got the calibration code from the ontario folder. I'll ping Mike (if he did the calibrations previously) to try to get this sorted out.
```
library(McMasterPandemic)
library(tidyverse)
library(ggplot2)
theme_set(theme_bw())
library(anytime) ## required when working with OLD calibrations

load("refactor/ontario-rda/ONcalib_2021May17.rda")
end_date <- as.Date(ont_cal1$mle2@data$end_date) + 30
prediction_new <- predict(ont_cal1,end_date=end_date) %>% filter(! (var %in% c('cumRep')))

load("inst/testdata/ONcalib_2020Jun01.rda")
end_date <- as.Date(ont_cal1$mle2@data$end_date) + 30
prediction_old <- predict(ont_cal1,end_date=end_date) %>% filter(! (var %in% c('cumRep')))

replace_na <- function(x) {x[is.na(x)]<- 0; x }
stopifnot(all(prediction_new$date == prediction_old$date))
stopifnot(all(prediction_new$var == prediction_old$var))
stopifnot(all(prediction_new$vtype == prediction_old$vtype))
merged <- dplyr::inner_join(prediction_new, prediction_old, by=c("date", "var", "vtype"), suffix=c("_new", "_old")) %>%
  mutate(value_new = replace_na(value_new), value_old = replace_na(value_old)) %>%
  mutate(abs_diff = abs(value_new-value_old))


ggplot_df <- merged %>% filter(var=='incidence')
ggplot(ggplot_df) +
  theme(text=element_text(size=20))+
  geom_line(aes(x=date, y=value_new, color='new'), size=1) +
  geom_line(aes(x=date, y=value_old, color='old'), size=1) +
  labs(x='date', y='incidence', title='New vs old prediction discrepancies', col='')
ggsave('refactor/ontario-rda/discrepancies.png')
``` 

![discrepancies](https://user-images.githubusercontent.com/43548362/118482191-62b7aa00-b6e2-11eb-8c2b-094d2101894b.png)

**Comment by wzmli** [comment]
It is unclear to me the motive behind this experiment. 
I just pushed ontario/ON_june1.R, follow the instructions and you can recreate the old calibration.

To answer the question why you are getting this plot, there are lots of changes inside the guts of the software. Maybe it is better to update the test and get rid of the old RData.

**Comment by bbolker** [comment]
@Apeirogons , I think we're going to punt on this and declare it "too old".  We should set up some slow-ish calibrations to run once in a while ....
