### ISSUE TITLE
Fix undocumented code object warnings in R-CMD-check

### ISSUE THREAD

**Issue by Apeirogons** [bbolker/McMasterPandemic#32]
Undocumented arguments in documentation object 'show_ratemat'
     'blocksize' 'block_col'

   Undocumented code objects:
     'bd' 'ont_all_sub'
   Undocumented data sets:
     'bd' 'ont_all_sub'

**Comment by bbolker** [comment]
The doc arguments are my fault. This is resolved on the `bmb_devel` branch. We could either cherry-pick the relevant commits (I think `git cherry-pick 3184e0c5` would do it) or merge `bmb_devel` to master (it currently passes `check()` *except* for the undocumented code objects ...)

**Comment by Apeirogons** [comment]
I fixed the undocumented code objects (add to R/data.R). I also resolved the show_ratemat problems, but we should probably use your documentation for that instead.
