### ISSUE TITLE
modify time_args setup to allow fixed+calibrated time args

### ISSUE THREAD

**Issue by bbolker** [bbolker/McMasterPandemic#37]
(Getting this down quickly before I forget, will probably edit more in the future. Comments welcome from everyone, especially @wzmli @papsti )

Proposed modification of API to solve a couple of problems: (1) specifying all of the components of a breakpoint model separately (break dates, starting values for calibration, symbol to change) is awkward; (2) it is not currently easy to have a *time-varying* but *fixed* (non-calibrated) parameter [I believe @wzmli has hacked around this by setting a narrow prior; there may be other hacks].

The present API for calibration (using `calibrate` + `run_sim_breaks`) is that `time_args` gets a list including `break_dates` and (optionally) `Symbol` (if not specified this defaults to "beta0"); all time-varying parameters are assumed to be calibrated, and their starting values are specified as `[link_]value` in `opt_pars`.

Proposed new structure:

- `time_args` will get a single data frame called `params_timevar`, containing columns `Date`, `Symbol`, `Relative_value`; the `Relative_value` column will be set to `NA` for any calibrated parameters
- starting values for calibrated parameters will (still) be specified as `[link_]value` in `opt_pars`
- `run_sim_break` will substitute back-transformed params into `params_timevar` as follows:
```r
params_timevar <- within(time_args$params_timevar,
                                         Relative_value[is.na(Relative_value)] <- extra_pars$value)
```

## Benefits

- allows fixed (non-calibrated) time-varying parameters without hacks
- keeps elements of time variation (date, symbol, rel value) together in a single data frame
- specifying `time_args$params_timevar` (rather than making `time_args` a top-level argument) preserves compatibility with `run_sim_loglin`
- removing the "Symbol==`beta0` by default" option will prevent errors/confusion (as long as we're going to break backward compatibility anyway)

## Drawbacks

- Breaks back compatibility
- Doesn't currently allow *absolute* values to be set. This could be done by allowing an `Absolute_value` column - but that wouldn't play well with identifying calibrated parameters by `NA` locations!  Would it be better to shift `params_timevar` to having a `value` column and a `type` (= "relative" or "absolute") column? (Is it OK to assume that `type` is "relative" if not specified? Or better to be explicit?
- Forces a single link function (if any) for the entire `values` parameter, i.e. we can't have some elements (which might represent different parameters with different constraints) with log and others with logit. This can be worked around somewhat by priors (e.g. if we want to restrict lockdown effects to a decrease in beta0 (0<rel_value<1) we can specify a log link and a prior concentrated below 0).  Is this a major limitation/something we should think about now?

I intend to work on this in the very near future, so timely comments would be welcome.

This will need to work slightly differently for `run_sim_loglin` (which is going to require bigger changes/refactoring anyway ...)

**Comment by papsti** [comment]
@bbolker a nudge, as promised 😊

**Comment by bbolker** [comment]
I think it's just about done. Cleaning up tests now. I think you should be able to try it out (on the `bmb_devel` branch, or I could be brave and submit a PR to master ...

The one thing that occurs to me in coding this is that I want to try to relabel `extra_pars$value` as something like `extra_pars$time_value`.

**Comment by bbolker** [comment]
OK, it passes `devtools::check()` (finally!)  Can you give it a spin? 

At present the `run_sim_loglin` machinery assumes that the parameters in `opt_pars` will be called `time_pars` (this is the vector to multiply by the model matrix to get the time-varying parameters: **run_sim_loglin badly needs to be refactored/extended anyway**; the `run_sim_break` machinery assumes they are called `value`.  Don't know whether to try to change the latter now, while I'm mucking around with things anyway.

**Comment by papsti** [comment]
Can you clarify the correct format of `opt_pars`? I'm using what I thought was the correct old format, e.g.

```
opt_pars <- list(
  params = c(beta0 = 1),
  rel_beta0 = 1.1
)

print(opt_pars)

$params
beta0 
    1 

$rel_beta0
[1] 1.1
```

and I'm getting a problem with this line

```
params_timevar <- within(time_args$params_timevar,
                                         Relative_value[is.na(Relative_value)] <- extra_pars$value)
```

Here I have `time_args = list(params_timevar = params_timevar)` where `params_timevar` looks like

```
        Date            Symbol Relative_value
1 2020-04-01             beta0             NA
2 2020-02-01 vax_doses_per_day          0e+00
3 2020-04-15 vax_doses_per_day          2e+05
```

I know `extra_pars` is derived from `opt_pars` somewhere in `calibrate()`, but I can't figure out how/when.  When I inspect `extra_pars` during a calibration with `opt_pars` as above, it's just a list that looks like this:

```
$rel_beta0
[1] 1.1
```

There's no `value` column... 

Here's a reprex that will only work on the `ip_devel` branch (I've merged your changes from `bmb_devel` into `ip_devel`):

```
## SETUP

## sim dates
start_date <- "2020-02-01"
end_date <- "2020-09-01"

original_beta0 <- 1

base_params <- update(read_params("PHAC.csv")
                      , N = 14e6
                      , beta0 = original_beta0
                      , obs_disp = 200
)

## vax params
vax_doses_per_day <- 1 ## setting to 1 so that we can use Relative_value in time_pars as if it is an absolute value
vax_params <- expand_params_vax(base_params,
                                vax_doses_per_day = vax_doses_per_day)

## time-varying parameters
time_pars <- data.frame(Date=c("2020-04-01", # beta date
                               start_date, "2020-04-15"), # vax dates
                        Symbol=c("beta0",
                                 "vax_doses_per_day", "vax_doses_per_day"),
                        Relative_value=c(1.1, 
                                         0, 2e5)) # vax off initially then suddenly on

## GENERATE SYNTHETIC REPORTS

res_vax <- run_sim(vax_params, make_state(params = vax_params),
                   start_date = start_date,
                   end_date = end_date,
                   params_timevar = time_pars,
                   stoch=c(obs=TRUE, proc = FALSE),
                   step_args = list(do_hazard = TRUE),
                   condense = TRUE,
                   condense_args = list(keep_all = TRUE,
                                        add_reports = TRUE))

report_data <- (res_vax
                %>% mutate(value=round(report), var="report")
                %>% select(date, value, var)
                %>% na.omit()
)

## CALIBRATE

## set up calibration initial conditions
opt_pars <- list(
  params = c(beta0 = original_beta0),
  rel_beta0 = time_pars$Relative_value[which(time_pars$Symbol == "beta0")]
)

params_timevar <- time_pars
params_timevar$Relative_value[which(params_timevar$Symbol == "beta0")] <- NA

## update time pars so that we don't fix beta0

fitted_mod_vax <- calibrate(
  data = report_data
  , start_date = start_date
  , base_params = vax_params
  , opt_pars = opt_pars
  , sim_args = list(step_args = list(do_hazard = TRUE))
  , time_args = list(params_timevar = params_timevar)
)
```

The error is

```
Error in Relative_value[rvals] <- extra_pars$value : 
  replacement has length zero
```

**Comment by papsti** [comment]
btw, the above reprex shows an example of how to get *absolute* time-varying parameters (in the setup of `vax_doses_per_day`), so it is possible with the current implementation, even if it's not the most user friendly.

**Comment by bbolker** [comment]
Huh, I think I completely missed this when you posted it. Is it still relevant ... ?

**Comment by papsti** [comment]
Nope, we covered it in the meeting yesterday. The issue was that I didn't realize the relative values column was (then) renamed to `value` in `opt_pars`. Now that we've decided to rename this column to `[link_]time_params` (and this is documented in `vignettes/calibration.rmd`), I'm happy!

**Comment by ZachLevine-11** [comment]
one question! would this change anything for the Shiny/for run_sim, specifically? Currently, time varying params use the params_timevar approach I believe

**Comment by papsti** [comment]
nope, this is just a change in how time-varying parameters are specified for `calibrate()`. the sim stuff is untouched.

**Comment by ZachLevine-11** [comment]
Got it! Thanks.
