### ISSUE TITLE
implement pkgdown

### ISSUE THREAD

**Issue by bbolker** [bbolker/McMasterPandemic#42]

**Comment by bbolker** [comment]
This is done, except for cleanup which is covered in #46 (thanks @Apeirogons !)

**Comment by bbolker** [comment]
Oops. I'm reopening this until we have some documentation for how to rebuild the `pkgdown` site (or possibly a GH action trigger, but that could be split off as a separate issue)

**Comment by bbolker** [comment]
I made `site-update` (and `site-update-lazy`) make rules.

**Comment by Apeirogons** [comment]
I don't get duplicated tabs when running pkgdown.extras::build_site(). Can you try again and see if it was a one-time issue?

**Comment by Apeirogons** [comment]
Added a GitHub Action for site rebuild; can't seem to get the on-push event to trigger reliably. I'm setting it to use workflow_dispatch to trigger the site rebuild for now.
