### ISSUE TITLE
explore faster sweep on sparse matrices: 

### ISSUE THREAD

**Issue by matthewcso** [bbolker/McMasterPandemic#52]
https://stackoverflow.com/questions/55407656/r-sweep-on-a-sparse-matrix https://gallery.rcpp.org/articles/sparse-matrix-class/ https://github.com/zdebruine/RcppSparse

**Comment by matthewcso** [comment]
**I actually didn't think of the very simple solution: instead of sweep or anything fancy, just use the simple expression M*v. This appears to be faster on both dense (base R) matrices, and sparse (dgCmatrix).**

The current approach ` t(t(M) * rep(v, rep.int(nrow(M), length(v))))` doesn't even work on dgCmatrix objects. I don't see any reason why not to change this.

Dense matrices:
```
> microbenchmark(sweep(M, v, MARGIN = 1, FUN = "*"))
Unit: microseconds
                               expr  min   lq   mean median    uq   max neval
 sweep(M, v, MARGIN = 1, FUN = "*") 32.9 33.9 42.463     35 40.85 132.8   100
> microbenchmark(t(t(M) * rep(v, rep.int(nrow(M), length(v)))))
Unit: microseconds
                                          expr  min   lq   mean median    uq max neval
 t(t(M) * rep(v, rep.int(nrow(M), length(v)))) 17.3 18.8 23.992  20.55 24.45  78   100
> microbenchmark( M * v)
Unit: nanoseconds
  expr min   lq mean median   uq   max neval
 M * v 800 1000 1435   1100 1450 11000   100
```

Sparse matrices:
```
> microbenchmark(sweep_sparse(M, margin=1, v, fun = "*"))
Unit: microseconds
                                      expr  min   lq   mean median    uq    max neval
 sweep_sparse(M, margin = 1, v, fun = "*") 13.4 13.6 61.074     14 14.75 4567.3   100
> microbenchmark(sweep(M, v, MARGIN = 1, FUN = "*"))
Unit: milliseconds
                               expr   min     lq     mean  median      uq   max neval
 sweep(M, v, MARGIN = 1, FUN = "*") 1.274 1.3646 1.499452 1.46255 1.58535 2.317   100
> microbenchmark(M * v)
Unit: microseconds
  expr  min   lq   mean median    uq   max neval
 M * v 39.4 40.1 44.357   40.4 41.45 185.9   100
```

Full code can be found in refactor/benchmark.R on the new matt_devel branch (that I'm about to create).

**Comment by matthewcso** [comment]
Just pasting refactor/benchmark.R here. Microbenchmarks are pretty similar with different matrices. `stopifnot` is used to show that M*v is equivalent to the previous sweep statement.

```
library(testthat)
library(microbenchmark)
library(Matrix)

sweep_sparse <- function(x, margin, stats, fun = "*") {
  f <- match.fun(fun)
  if (margin == 1) {
    idx <- x@i + 1
  } else {
    idx <- x@j + 1
  }
  x@x <- f(x@x, stats[idx])
  return(x)
}

generate_dense_matrix <- function(n){
  names <- c(99:(99 + n - 1))

  M <- matrix(runif(n * n), nrow = n, ncol = n)
  rownames(M) <- names
  colnames(M) <- names
  v <- runif(n)
  names(v) <- names
  return(list(M=M, v=v))
}

generate_sparse_matrix <- function(n, sparsity=0.1){
  names <- c(99:(99 + n - 1))

  M <- rsparsematrix(nrow=n, ncol=n, density = sparsity, rand.x = runif)
  rownames(M) <- names
  colnames(M) <- names
  v <- runif(n)
  names(v) <- names
  return(list(M=M, v=v))
}

# -----------------------------------------------------------------------
L <- generate_dense_matrix(20)
M <- L$M
v <- L$v

baseline <- sweep(M, v, MARGIN = 1, FUN = "*")
other_0 <- t(t(M) * rep(v, rep.int(nrow(M), length(v))))
other_1 = M * v

stopifnot(baseline == other_0)
stopifnot(baseline == other_1)

microbenchmark(sweep(M, v, MARGIN = 1, FUN = "*"))
microbenchmark(t(t(M) * rep(v, rep.int(nrow(M), length(v)))))
microbenchmark( M * v)
# -----------------------------------------------------------------------
# quick checks to ensure equivalence of these methods
L <- generate_sparse_matrix(20)
M <- L$M
v <- L$v

baseline <- sweep(M, v, MARGIN = 1, FUN = "*")
other_0 <- M * v
other_1 <- sweep_sparse(M, margin=1, v, fun = "*")


stopifnot(all(baseline == other_0))
stopifnot(all(baseline == other_1))
microbenchmark(sweep_sparse(M, margin=1, v, fun = "*"))
microbenchmark(sweep(M, v, MARGIN = 1, FUN = "*"))
microbenchmark(M * v)
```

**Comment by bbolker** [comment]
Yes. As long as we want to do *columnwise* sweeping, R's column-order matrix storage and its default vector-replication machinery will do everything for us.  I still think we could squeeze out a tiny bit more performance by implementing in C++ but maybe not worth the effort right now.

Do we actually know how much this sort of stuff typically affects the overall runtime? (It's a bit of a pain to find out, since we have to implement both approaches internally and/or switch back and forth between code bases ...)

**Comment by matthewcso** [comment]
I could run the profiler again, but I believe it was a 5-10% performance speedup for non-stochastic simulations. However, I'm recommending using M*v for column-wise sweeps on both base R and dgCmatrices... is implementing multiple approaches still an issue in this case?

**Comment by matthewcso** [comment]
I did the profiling now; for calibration, the old sweep used 5680 ms with 54930 total, while M*v took 240 ms on a run with 41240 total. Of course, the total runtime is affected by what is going on in my computer; however, I think it's a fairly significant increase.
