### ISSUE TITLE
Dashes on lines should match the scale of the vaccination rates…

### ISSUE THREAD

**Issue by bwinton** [bbolker/McMasterPandemic#57]
That's not really what I mean, but I'm not sure how to summarize it, so here's a bit of a wall of text.

Currently, on https://mac-theobio.github.io/forecasts/outputs/McMasterOntarioForecastsBlog2021-06-05 the Forecast results graph has:
```
--------- 142k
- - - - - - 180k
--  --  -- 213k
```
or, put another way,
the longest length of dash <=> the lowest number of doses.
The shortest length <=> the middle number.
The middlest length <=> the highest number.

I think it might be easier to read if the mapping increased from "- - -" to "-- -- --" to "------" (or backwards).

I'm not in academia, so there may be reasons the legend is the way it is that I don't know about, but if not hopefully it's a small change. 🙂

**Comment by papsti** [comment]
great idea! thanks for the suggestion :blush:

here's what the plot looks like with your suggestion incorporated:

![forecast_2021-06-05](https://user-images.githubusercontent.com/21325059/122838724-ac3c7b80-d2c4-11eb-9b45-9a0857f5a53f.png)

it should be live on the blog shortly.

**Comment by bbolker** [comment]
Might even be worth fussing with the lengths of the dash patterns a little bit more (short- and long-dashes are hard to distinguish in this example)?

**Comment by papsti** [comment]
good point... i was hoping that the keys were wide enough that the short and long dash would be easily distinguishable.

how's this?

![forecast_2021-06-05](https://user-images.githubusercontent.com/21325059/122839965-181fe380-d2c7-11eb-8887-68ddb067bcc7.png)

**Comment by bbolker** [comment]
Much better IMO.
